when@dev:
    zenstruck_foundry:
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true

when@test:
    zenstruck_foundry:
        persistence:
            # On répète la config ici pour l'environnement de test
            flush_once: true
